services:
  - type: web
    name: heart-backend
    env: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app --chdir back --timeout 120
    envVars:
      - key: PORT
        scope: runtime
      - key: ENVIRONMENT
        value: production
      - key: FLASK_ENV
        value: production
